/**
 * Tokens de diseño extraídos de DESIGN.md (Industrial Electromechanical B2B UI)
 * Base de diseño para primer-agente.
 */

export const DESIGN_TOKENS = {
  name: "Industrial Electromechanical B2B UI",
  style: "Corporate / Modern & Structured Minimalism",
  colors: {
    surface: "#f5fafd",
    surfaceDim: "#d5dbde",
    surfaceBright: "#f5fafd",
    surfaceContainerLowest: "#ffffff",
    surfaceContainerLow: "#eff4f7",
    surfaceContainer: "#e9eff1",
    surfaceContainerHigh: "#e3e9ec",
    surfaceContainerHighest: "#dee3e6",
    onSurface: "#171c1f",
    onSurfaceVariant: "#3d494d",
    inverseSurface: "#2b3134",
    inverseOnSurface: "#ecf2f4",
    outline: "#6d797e",
    outlineVariant: "#bcc9ce",
    surfaceTint: "#00677d",
    primary: "#00677d",
    onPrimary: "#ffffff",
    primaryContainer: "#00b4d8",
    onPrimaryContainer: "#00414f",
    inversePrimary: "#4cd6fb",
    secondary: "#006399",
    onSecondary: "#ffffff",
    secondaryContainer: "#67bafd",
    onSecondaryContainer: "#004972",
    tertiary: "#006875",
    onTertiary: "#ffffff",
    tertiaryContainer: "#60b1bf",
    onTertiaryContainer: "#00424a",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdad6",
    onErrorContainer: "#93000a",
    primaryFixed: "#b3ebff",
    primaryFixedDim: "#4cd6fb",
    onPrimaryFixed: "#001f27",
    onPrimaryFixedVariant: "#004e5f",
    secondaryFixed: "#cde5ff",
    secondaryFixedDim: "#94ccff",
    onSecondaryFixed: "#001d32",
    onSecondaryFixedVariant: "#004b74",
    tertiaryFixed: "#9feffe",
    tertiaryFixedDim: "#83d3e1",
    onTertiaryFixed: "#001f24",
    onTertiaryFixedVariant: "#004f59",
    background: "#f5fafd",
    onBackground: "#171c1f",
    surfaceVariant: "#dee3e6",
  },
  typography: {
    heading: "var(--font-ibm-plex-sans), sans-serif",
    body: "var(--font-inter), sans-serif",
    mono: "var(--font-jetbrains-mono), monospace",
  },
  borderRadius: {
    sm: "0.125rem",
    default: "0.25rem",
    md: "0.375rem",
    lg: "0.5rem",
    xl: "0.75rem",
    full: "9999px",
  },
  spacing: {
    gutter: "16px",
    margin: "24px",
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    "2xl": "48px",
  },
} as const;

export type DesignTokens = typeof DESIGN_TOKENS;
